// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';

// import '../models/transaction.dart';

// class TransactionNotifier extends Notifier<List<TransactionModel>> {
//   final FirebaseFirestore _firestore = FirebaseFirestore.instance;
//   final FirebaseAuth _auth = FirebaseAuth.instance;

//   @override
//   List<TransactionModel> build() => const [];

//   CollectionReference<Map<String, dynamic>> get _transactionsRef {
//     final uid = _auth.currentUser!.uid;
//     return _firestore.collection('users').doc(uid).collection('transactions');
//   }

//   Future<void> loadTransactions() async {
//     final snapshot = await _transactionsRef
//         .orderBy('occurredAt', descending: true)
//         .get();

//     final list = snapshot.docs
//         .map((doc) => TransactionModel.fromMap(doc.id, doc.data()))
//         .toList();

//     state = list;
//   }

//   Future<void> logExpense({
//     required double amount,
//     required String categoryId,
//     String? note,
//     TransactionSource source = TransactionSource.manual,
//   }) async {
//     final now = DateTime.now();
//     final transaction = TransactionModel(
//       id: now.millisecondsSinceEpoch.toString(),
//       amount: amount,
//       categoryId: categoryId,
//       note: note,
//       occurredAt: now,
//       source: source,
//       recurringItemId: null,
//       createdAt: now,
//       updatedAt: now,
//     );

//     await _transactionsRef.doc(transaction.id).set(transaction.toMap());
//     state = [transaction, ...state];
//   }

//   Future<void> addTransaction(TransactionModel transaction) async {
//     await _transactionsRef.doc(transaction.id).set(transaction.toMap());
//     state = [transaction, ...state];
//   }

//   Future<void> updateTransaction(TransactionModel transaction) async {
//     await _transactionsRef.doc(transaction.id).update(transaction.toMap());
//     state = [
//       for (final item in state)
//         if (item.id == transaction.id) transaction else item,
//     ];
//   }

//   Future<void> deleteTransaction(String id) async {
//     await _transactionsRef.doc(id).delete();
//     state = state.where((item) => item.id != id).toList();
//   }
// }

// final transactionProvider =
//     NotifierProvider<TransactionNotifier, List<TransactionModel>>(
//       TransactionNotifier.new,
//     );

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'dart:math';

import '../models/transaction.dart';

//our state is a list of Transaction models
//List<TransactionModel>

class TransactionProvider extends Notifier<List<TransactionModel>> {
  final FirebaseFirestore firestore = FirebaseFirestore.instance;
  final FirebaseAuth auth = FirebaseAuth.instance;

  //collection reference is a datatype provided by firestore
  //collection -> document
  CollectionReference<Map<String, dynamic>> get transactionsRef {
    final user = auth.currentUser!;
    return firestore
        .collection('users')
        .doc(user.uid)
        .collection('transactions');
  }

  @override
  List<TransactionModel> build() {
    return const [];
    //initialize with empty list
  }

  //converting each document into a Transaction model object
  Future<void> loadTransactions() async {
    final rawTransactions = await transactionsRef.get();
    final transactions = rawTransactions.docs.map((doc) {
      return fromMap(doc.id, doc.data());
    }).toList();
    state = transactions;
  }

  //.add makes a new document in firestore with a unique id generated by firestore
  // .doc().set() makes a new document with a unique id generated by us
  Future<void> addTransaction(
    double amount,
    String category,
    String? note,
    DateTime occurredAt,
  ) async {
    final doc = transactionsRef.doc();
    final transaction = TransactionModel(
      amount: amount,
      category: category,
      note: note,
      id: doc.id,
      occurredAt: occurredAt,
    );
    await doc.set(transaction.toMap());
    state = [transaction, ...state];
  }

  //state is of type List<TransactionModel> so transaction is one TransactionModel type.
  Future<void> removeTransaction(String id) async {
    await transactionsRef.doc(id).delete();
    state = state.where((transaction) => transaction.id != id).toList();
  }

  Future<void> updateTransaction(TransactionModel transaction) async {
    await transactionsRef.doc(transaction.id).update(transaction.toMap());
    //if in state (list of transactions) the transaction id matches the id in the transaction
    //we are trying to update then update it else keep same.
    state = state.map((t) => t.id == transaction.id ? transaction : t).toList();
  }

  Future<void> seedDemoData() async {
    final random = Random();
    final today = DateTime.now();

    final categories = [
      'Food',
      'Transport',
      'Laundry',
      'Shopping',
      'Entertainment',
      'Education',
      'Health',
    ];

    for (int i = 0; i < 84; i++) {
      final date = DateTime(
        today.year,
        today.month,
        today.day,
      ).subtract(Duration(days: i));

      // Around 25% of days have no spending.
      if (random.nextDouble() < 0.25) {
        continue;
      }

      // Most days have 1 transaction, some have 2 or 3.
      final transactionCount = random.nextDouble() < 0.7
          ? 1
          : random.nextInt(2) + 2;

      for (int j = 0; j < transactionCount; j++) {
        final category = categories[random.nextInt(categories.length)];

        // Strongly favors smaller amounts.
        final r = random.nextDouble();
        final amount = 20 + (r * r * 480);

        // Random time during the day.
        final occurredAt = DateTime(
          date.year,
          date.month,
          date.day,
          8 + random.nextInt(14),
          random.nextInt(60),
        );

        final doc = transactionsRef.doc();

        final transaction = TransactionModel(
          amount: amount.roundToDouble(),
          category: category,
          note: 'Demo data',
          id: doc.id,
          occurredAt: occurredAt,
        );

        await doc.set(transaction.toMap());
      }
    }

    await loadTransactions();
  }

  Future<void> removeDemoData() async {
    final snapshot = await transactionsRef.get();

    for (final doc in snapshot.docs) {
      final data = doc.data();

      if (data['note'] == 'Demo data') {
        await doc.reference.delete();
      }
    }

    await loadTransactions();
  }
}

final transactionProvider =
    NotifierProvider<TransactionProvider, List<TransactionModel>>(
      TransactionProvider.new,
    );
