// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkl3_hV28Mp3piud2n3BuKC-yzSGvoEJk',
    appId: '1:399035929737:web:b90c7b1df4f106b6ede258',
    messagingSenderId: '399035929737',
    projectId: 'spendly-617e1',
    authDomain: 'spendly-617e1.firebaseapp.com',
    storageBucket: 'spendly-617e1.firebasestorage.app',
    measurementId: 'G-JD4PZ45PN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rkKzM9bLScoI0zZghigrnrEUZ2ztXow',
    appId: '1:399035929737:android:3d93fb487164f890ede258',
    messagingSenderId: '399035929737',
    projectId: 'spendly-617e1',
    storageBucket: 'spendly-617e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkl3_hV28Mp3piud2n3BuKC-yzSGvoEJk',
    appId: '1:399035929737:web:b162e0336cbe7201ede258',
    messagingSenderId: '399035929737',
    projectId: 'spendly-617e1',
    authDomain: 'spendly-617e1.firebaseapp.com',
    storageBucket: 'spendly-617e1.firebasestorage.app',
    measurementId: 'G-JB89HLDL98',
  );
}
